package controllers.line

object Constants {	
	// val REDIS_HOST = "www.jookershop.com"
	val REDIS_HOST = "localhost"
	// val REDIS_HOST = "104.199.143.166"
	

	val REDIS_KEY_ACTIVE_USER = "AUSR"
	val REDIS_KEY_HOT_USER = "HUSR"
	val REDIS_KEY_TODAY_USER = "TUSR"
	val REDIS_KEY_USER = "USR"

	val REDIS_KEY_ACCOUNT = "RKA"	
	val REDIS_KEY_ACCOUNT_MAN = "RKAMN"
	val REDIS_KEY_ACCOUNT_WOMEN = "RKAWN"

	val REDIS_KEY_INTEREST = "IT:"
	val REDIS_KEY_INTEREST_M = "ITM:"
	val REDIS_KEY_INTEREST_F = "ITF:"

	val REDIS_KEY_PLACE = "PL:"
	val REDIS_KEY_PLACE_M = "PLM:"
	val REDIS_KEY_PLACE_F = "PLF:"	

	val REDIS_KEY_CAREER = "CA:"
	val REDIS_KEY_CAREER_M = "CAM:"
	val REDIS_KEY_CAREER_F = "CAF:"

	val REDIS_KEY_OLD = "OL:"
	val REDIS_KEY_OLD_M = "OLM:"
	val REDIS_KEY_OLD_F = "OLF:"

	val REDIS_KEY_CONSTELLATION = "CL:"
	val REDIS_KEY_CONSTELLATION_M = "CLM:"
	val REDIS_KEY_CONSTELLATION_F = "CLF:"

	val REDIS_KEY_MOTION = "MO:"
	val REDIS_KEY_MOTION_M = "MOM:"
	val REDIS_KEY_MOTION_F = "MOF:"

	val REDIS_KEY_CHAT = "CHAT"

	val REDIS_KEY_REPORT_INTEREST = "RPT:"
	val REDIS_KEY_REPORT_PLACE = "RPP:"
	val REDIS_KEY_REPORT_CAREER = "RPC:"
	val REDIS_KEY_REPORT_OLD = "RPO:"
	val REDIS_KEY_REPORT_CONSTELLATION = "RPCL:"
	val REDIS_KEY_REPORT_MOTION = "RPM:"
	val REDIS_KEY_REPORT = "REP:"

	val REDIS_KEY_REPORT_ALL = "RPALL:"

	val REDIS_KEY_ONLINE = "ONL"

	val REDIS_KEY_POST = "POST"
	val REDIS_KEY_REPLY_POST = "RPOST"
	val REDIS_KEY_REPLY_POST_ID = "RPOSTD:"

	val REDIS_KEY_MSG = "LMSG"
	val REDIS_KEY_NOTIFICATION = "NOTIFY"

	val REDIS_KEY_NEW_MSG = "NMSG:"
	val REDIS_KEY_NEW_MSG_NOTI = "NMSGN"
	val REDIS_KEY_NEW_MSG_NOTI_LAST_U = "NMSGNU"

	val REDIS_KEY_TRACE = "TRACE"
	val REDIS_KEY_HIDE = "HIDE"

	val REDIS_KEY_DISCUSS_ROOM = "DR"

	val REDIS_KEY_GAME_TOTALS = "TGAME"
	val REDIS_KEY_GUESS_GAME_PLAY_ITEM = "GPLAYITEM"
	val REDIS_KEY_GUESS_QUEUE = "gq"

	val REDIS_KEY_GAME_WIN_NUMBER = "GWN"
	val REDIS_KEY_GAME_WINER = "GWER"	
	val REDIS_KEY_GAME_HISTORY = "GH:"
	val REDIS_KEY_GAME_GUESS_CURRENT = "GGC"
	val REDIS_KEY_GAME_GUESS_BIG = "GGB"
	val REDIS_KEY_GAME_GUESS_SMALL = "GGS"
	val REDIS_KEY_GAME_GUESS_START_TIME = "GGST"
	val REDIS_KEY_GAME_CHECK_TIME = "GCT"
	val REDIS_KEY_GAME_GUESS_FINISH = "GGF"
	val REDIS_KEY_GCM = "RGCM"

	val REDIS_KEY_GIFT_LINE = "GL"
	val REDIS_KEY_GIFT_LINE_CHECK_TIME = "GLCT"
	val REDIS_KEY_GIFT_LINE_NEW_CHECK_TIME = "GLNCT"	
	val REDIS_KEY_GIFT_LINE_PLAY_COUNT = "GLPC"
	val REDIS_KEY_GIFT_LINE_CHECK_COUNT = "GLCC"
	val REDIS_KEY_GIFT_LINE_ACHIVE = "GLA:"

	val REDIS_KEY_GIFT_LINE_TOPIC = "GLT"
	val REDIS_KEY_GIFT_LINE_TOPIC_CHECK_TIME = "GLTCT"
	val REDIS_KEY_GIFT_LINE_TOPIC_NEW_CHECK_TIME = "GLTNCT"	
	val REDIS_KEY_GIFT_LINE_TOPIC_PLAY_COUNT = "GLTPC"
	val REDIS_KEY_GIFT_LINE_TOPIC_CHECK_COUNT = "GLTCC"
	val REDIS_KEY_GIFT_LINE_TOPIC_ACHIVE = "GLTA:"


	val REDIS_KEY_GIFT_LINE_PRODUCT = "GLP"
	val REDIS_KEY_GIFT_LINE_PRODUCT_CHECK_TIME = "GLPCT"
	val REDIS_KEY_GIFT_LINE_PRODUCT_NEW_CHECK_TIME = "GLPNCT"	
	val REDIS_KEY_GIFT_LINE_PRODUCT_PLAY_COUNT = "GLPPC"
	val REDIS_KEY_GIFT_LINE_PRODUCT_CHECK_COUNT = "GLPCC"
	val REDIS_KEY_GIFT_LINE_PRODUCT_ACHIVE = "GLPA:"

	val REDIS_KEY_GIFT_MONEY = "GM"
	val REDIS_KEY_GIFT_MONEY_CHECK_TIME = "GMCT"
	val REDIS_KEY_GIFT_MONEY_NEW_CHECK_TIME = "GMNCT"	
	val REDIS_KEY_GIFT_MONEY_PLAY_COUNT = "GMPC"
	val REDIS_KEY_GIFT_MONEY_CHECK_COUNT = "GMCC"
	val REDIS_KEY_GIFT_MONEY_ACHIVE = "GMA:"


	val REDIS_KEY_GIFT_BAG = "GB"
	val REDIS_KEY_GIFT_BAG_CHECK_TIME = "GBCT"
	val REDIS_KEY_GIFT_BAG_NEW_CHECK_TIME = "GBNCT"	
	val REDIS_KEY_GIFT_BAG_PLAY_COUNT = "GBPC"
	val REDIS_KEY_GIFT_BAG_CHECK_COUNT = "GBCC"
	val REDIS_KEY_GIFT_BAG_ACHIVE = "GBA:"

	val REDIS_KEY_GIFT_SE = "GE"
	val REDIS_KEY_GIFT_SE_CHECK_TIME = "GSCT"
	val REDIS_KEY_GIFT_SE_NEW_CHECK_TIME = "GSNCT"	
	val REDIS_KEY_GIFT_SE_PLAY_COUNT = "GSPC"
	val REDIS_KEY_GIFT_SE_CHECK_COUNT = "GSCC"
	val REDIS_KEY_GIFT_SE_ACHIVE = "GSA:"


	val REDIS_KEY_GIFT_RANDOM_KEY = "GRK"
	val REDIS_KEY_GIFT_CODE_KEY = "GCK"
	val REDIS_KEY_ADMIN_MSG = "AM"

	val REDIS_KEY_GIFT_REPORT_LINE = "GRL"
	val REDIS_KEY_GIFT_REPORT_LINE_MSG = "GRLM"

	val REDIS_KEY_GIFT_REPORT_LINE_TOPIC = "GRLT"
	val REDIS_KEY_GIFT_REPORT_LINE_PRODUCT = "GRLP"
	val REDIS_KEY_GIFT_REPORT_MONEY = "GRM"
	val REDIS_KEY_GIFT_REPORT_BAG = "GRB"
	val REDIS_KEY_GIFT_REPORT_SE = "GRS"
	val REDIS_KEY_GIFT_TASKS = "GTS:"

	// val REDIS_KEY_GIFT_QUEUE = "GGQ:"
	val REDIS_KEY_GIFT_TQUEUE = "GZTQ:"
	val REDIS_KEY_GIFT_ZQUEUE = "GZQ:"
	val REDIS_KEY_GIFT_INCRBY = "GINC:"
	val REDIS_KEY_GIFT_HQUEUE = "GHQ"
	val REDIS_KEY_GIFT_NOW_SEND = "GNS:"



	// val REDIS_KEY_GIFT_LINE_QUEUE = "GLQ"
	// val REDIS_KEY_GIFT_MONEY_QUEUE = "GMQ"
	// val REDIS_KEY_GIFT_BAG_QUEUE = "GBQ"
	// val REDIS_KEY_GIFT_SE_QUEUE = "GSQ"

	val ALL_INTERESTS_ID = List("1", "2", "3", "4", "5", "6","7","8","9","10","11","12","13", "14","15")
	val ALL_PLACES_ID = List("1", "2", "3", "4", "5", "6","7","8","9","10","11","12","13", "14","15","16","17","18")
	val ALL_CAREERS_ID = List("1", "2", "3", "4", "5", "6","7","8","9","10","11","12","13", "14","15","16","17")
	val ALL_OLDS_ID = List("1", "2", "3", "4", "5", "6","7","8")
	val ALL_CONSTELLATION_ID = List("1", "2", "3", "4", "5", "6","7","8", "9", "10", "11", "12")
	val ALL_MOTION_ID = List("1", "2", "3", "4", "5", "6","7","8","9","10","11","12","13", "14","15","16","17","18", "19","20","21")

}